#!/bin/bash
SUPABASE_URL="https://euivfkoulfaslbypmqyl.supabase.co"
ANON_KEY="sb_publishable_IUh06W472gFWIUdfTtrJ8w_Sa6vp1-v"
AUD_ID="ae59e1da-ea28-4ff0-8a9f-f3cc3cc56318"

PAYLOAD='[
  {"auditoria_id":"'"$AUD_ID"'","categoria":"ClickUp","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantas clientes da carteira foram atendidos dentro do mes?","qtd_avaliados":9,"qtd_conformes":9,"nota_pct":100,"conforme":"Conforme","observacao":"Alyne Cosmeticos, Rejuntamix, Marcelo Medeiros, Ramira, Primare, Seta, Academia Eugenio, Donna Classic, Ponto do Borracheiro, Wing Distribuidora. Cliente em tratativa com reuniao: Wing"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"WhatsApp","tipo_amostragem":"30% da carteira","tipo":"Resultado","pergunta":"Os clientes foram respondidos no ultimo turno e sem vacuos superiores a 24h uteis e sem reclamacoes explicitas?","qtd_avaliados":9,"qtd_conformes":9,"nota_pct":100,"conforme":"Conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Drive","tipo_amostragem":"30% da carteira","tipo":"Conformidade","pergunta":"Os clientes possuem gravacoes de reunioes na pasta gravacoes?","qtd_avaliados":9,"qtd_conformes":9,"nota_pct":100,"conforme":"Conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantos % dos clientes estao com meta batida da operacao? (Alianca)","qtd_avaliados":7,"qtd_conformes":3,"nota_pct":42.86,"conforme":"Nao conforme","observacao":"Academia Eugenio, Dotus, Ponto do Borracheiro"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantos % dos clientes estao com meta batida da operacao? (GSA)","qtd_avaliados":2,"qtd_conformes":1,"nota_pct":50,"conforme":"Nao conforme","observacao":"Alyne Cosmeticos"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantos % dos clientes estao com meta batida da operacao? (Todos os produtos)","qtd_avaliados":9,"qtd_conformes":4,"nota_pct":44.44,"conforme":"Nao conforme","observacao":"Academia Eugenio, Dotus, Alyne, Ponto do Borracheiro"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantos clientes tem em flags em Care?","qtd_avaliados":9,"qtd_conformes":2,"nota_pct":22.22,"conforme":"Nao conforme","observacao":"By Marcelo Medeiros, Gcpar"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantos clientes tem em flags em Danger?","qtd_avaliados":9,"qtd_conformes":4,"nota_pct":44.44,"conforme":"Nao conforme","observacao":"Cardan, Clarus, Estrela, Rejuntamix"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Resultado","pergunta":"Quantos clientes tem em flags em Safe?","qtd_avaliados":9,"qtd_conformes":4,"nota_pct":44.44,"conforme":"Nao conforme","observacao":"Academia Eugenio, Bebe Nasceu, Dotus, Primare Odontologia"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Drive","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"As entregas enviadas nos grupos de WhatsApp e descritas no ClickUp estao nos drives dos respectivos clientes?","qtd_avaliados":9,"qtd_conformes":9,"nota_pct":100,"conforme":"Conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"As flags estao preenchidas?","qtd_avaliados":19,"qtd_conformes":10,"nota_pct":52.63,"conforme":"Nao conforme","observacao":"Definir as flags: Alyne, Loks, Polipedras, Ponto do Borracheiro, Ramira Moda Fitness, Seta, Vera Lucia, Wing Distribuidora"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"As metas do cliente do mes anterior foram inseridas ate o dia 5 do mes subsequente?","qtd_avaliados":9,"qtd_conformes":8,"nota_pct":88.89,"conforme":"Conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"ClickUp","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"As tarefas com status sem reuniao ou tarefas atrasadas tem justificativas na ferramenta?","qtd_avaliados":16,"qtd_conformes":3,"nota_pct":18.75,"conforme":"Nao conforme","observacao":null,"encaminhamento":"ClickUp: Inserir justificativas nas reunioes com status sem reuniao. https://app.clickup.com/9010141244/v/l/5-90139212293-1"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"WhatsApp","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Nas ultimas 2 reunioes foram enviados um resumo/encaminhamento do que aconteceu na reuniao no grupo?","qtd_avaliados":9,"qtd_conformes":4,"nota_pct":44.44,"conforme":"Nao conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"ClickUp","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"O historico de comentarios narra a historia do projeto (descricoes das tarefas, transcricoes das reunioes)?","qtd_avaliados":9,"qtd_conformes":2,"nota_pct":22.22,"conforme":"Nao conforme","observacao":"Alyne Cosmeticos, Rejuntamix","encaminhamento":"ClickUp: Inserir transcricoes das reunioes: Seta, Donna Classic, Dotus, Polipedras, Academia Eugenio, Gcpar, Marcelo Medeiros"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Drive","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Os arquivos que nao sao ferramentas modelo estao em conformidade com a identidade visual da Vorp?","qtd_avaliados":9,"qtd_conformes":9,"nota_pct":100,"conforme":"Conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Os criterios das flags estao sendo seguidos?","qtd_avaliados":9,"qtd_conformes":4,"nota_pct":44.44,"conforme":"Nao conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Drive","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Os encaminhamentos estao nos drives dos clientes, atualizados e preenchidos corretamente?","qtd_avaliados":9,"qtd_conformes":3,"nota_pct":33.33,"conforme":"Nao conforme","observacao":"Dotus, Academia Eugenio, Alyne Cosmeticos","encaminhamento":"Drive: Revisar encaminhamentos Dotus e Seta. Criar plano tatico: Polipedras, Gcpar. Reorganizar pasta: Seta. Revisar plano incompleto: Marcelo Medeiros, Rejuntamix"},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Os realizados da meta dos clientes estao preenchidos sobre o Alianca e Alianca Pro?","qtd_avaliados":7,"qtd_conformes":6,"nota_pct":85.71,"conforme":"Conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"Vorp System","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Os realizados da meta dos clientes estao preenchidos sobre o GSA?","qtd_avaliados":2,"qtd_conformes":1,"nota_pct":50,"conforme":"Nao conforme","observacao":null},
  {"auditoria_id":"'"$AUD_ID"'","categoria":"ClickUp","tipo_amostragem":"Totalidade","tipo":"Conformidade","pergunta":"Se o consultor sair hoje, outro assume o projeto apenas lendo o ClickUp?","qtd_avaliados":9,"qtd_conformes":1,"nota_pct":11.11,"conforme":"Nao conforme","observacao":null}
]'

echo "$PAYLOAD" | curl -s -X POST "$SUPABASE_URL/rest/v1/auditoria_itens" \
  -H "apikey: $ANON_KEY" \
  -H "Authorization: Bearer $ANON_KEY" \
  -H "Content-Type: application/json" \
  -H "Prefer: return=minimal" \
  --data-binary @-

echo "STATUS: $?"
